spring:
  application:
  name: bookbookclub

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/bookbookclub?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: blossom913@
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
