spring:
  application:
  name: bookbookclub
  web:
    resources:
      static-locations: file:uploads/
  datasource:
    url: jdbc:mysql://localhost:3306/bookbookclub?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: blossom913@

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: workingsg913@gmail.com
    password: lbxr vwer mpkw mwlt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 78462701927-2cpml97no9s81gdt5fcus65ftvpm8jk3.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
          naver:
            client-id: aB9czdMTS4EGWChBW0hB
            client-secret: Fpq5ZvoqpG
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

custom:
  user:
    default-profile-image: /images/profile-images/default.jpg
    profile-image-upload-path: /Users/ddururiiiiiii/dev/bookbookclub/images/profile-images